config setup
    charondebug="ike 1, knl 1, cfg 1"

conn udm-site
    keyexchange=ikev2
    ike=aes256-sha256-modp2048
    esp=aes256-sha256-modp2048
    authby=psk

    left=%any
    leftid=@far-pi
    leftsubnet=192.168.40.0/24

    right=x.x.x.x
    rightid=@x.x.x.x
    rightsubnet=192.168.32.0/24,10.10.1.0/24,10.10.2.0/24,10.20.30.0/24,10.100.253.0/24,10.100.254.0/24

    dpddelay=10s
    dpdtimeout=40s
    dpdaction=restart
    closeaction=restart
    keyingtries=%forever
    reauth=no

    auto=start